### ISSUE TITLE
Unity crashing when --mmproj flag is added..

### ISSUE THREAD

**Issue by NOSCOPEdev** [undreamai/LLMUnity#207]
### Describe the bug

Hi, I am trying to implement multi model projection for this project, but unity crashes whenever i change the server command sent.         int slots = GetNumClients();

        string arguments = $"-m "{modelPath}"  -c {contextSize} -b {batchSize} --log-disable -np {slots}";
        if (remote) arguments += $" --port {port} --host 0.0.0.0";
        if (numThreadsToUse > 0) arguments += $" -t {numThreadsToUse}";
        if (loraPath != "") arguments += $" --lora "{loraPath}"";
        //changed part:
        if (MMprojModelLoc != "") arguments += $" --mmproj "{MMprojModelLoc}"";
        arguments += $" -ngl {numGPULayers}";
        return arguments; 

(this is the changed code btw)

This crashes unity when I press play.
Even in the current version of llama that this project uses, it is still possible to use  --mmproj.
If anyone can help, I would appreciate it immensely.

I don't really think this is an enhancement so I am putting it here on bugs. I know that this doesn't happen for anyone using the default project, but this still limits the project as it crashes unity so I think its justified to put it here. I am not really looking for a fix, rather a reason for this occurrence would suffice.

### LLMUnity version

2.1.0

### Operating System

Windows

**Comment by amakropoulos** [comment]
hi, thanks for the request!
I'll label it as enhancement. The reason is that Llama.cpp does not provide a high-level api (it is [wip](https://github.com/ggerganov/llama.cpp/issues/5215) for some time).
For that reason I have modified it to make it possible to be implemented as DLL (lib is [here](https://github.com/undreamai/LlamaLib)).
I don't support the full functionality because it needs some effort, so I add whatever is needed or requested :slightly_smiling_face: .

**Comment by NOSCOPEdev** [comment]
It works now! Thank you for the new lib!
