### ISSUE TITLE
Support for non CUDA or ROCm supported GPUs.

### ISSUE THREAD

**Issue by Flamerace** [undreamai/LLMUnity#228]
### Describe the feature

I wanted to know if it is possible to add the functionality of running inference on the GPU except for CUDA or ROCm support, like in Unity's sentis, which has GPU Compute and GPU pixel shader processing methods. My Rx 6600xt doesn't support ROCm, and older cards won't work either, plus Intel arc GPUs can benefit from this functionality.

**Comment by amakropoulos** [comment]
It's not possible because Sentis has very limited support for LLMs and deep learning in general.
It doesn't support all LLM layers, doesn't have tokenisation techniques and any other LLM options/ pre/post-processing.
It also needs compilation of onnx models to sentis and is slow.
It will be essentially rewriting llama.cpp from scratch (months of work) without real benefits.
Vulkan should support most GPUs, is it working for you?

**Comment by Flamerace** [comment]
> It's not possible because Sentis has very limited support for LLMs and deep learning in general. It doesn't support all LLM layers, doesn't have tokenisation techniques and any other LLM options/ pre/post-processing. It also needs compilation of onnx models to sentis and is slow. It will be essentially rewriting llama.cpp from scratch (months of work) without real benefits. Vulkan should support most GPUs, is it working for you?

Thanks for the help, previously when I tried to use GPU layer it didn't work, but surprisingly after I tried now it works. Thanks again.

**Comment by amakropoulos** [comment]
Amazing, thank you for the issue!
