### ISSUE TITLE
Context Size

### ISSUE THREAD

**Issue by 3inary** [undreamai/LLMUnity#270]
### Describe the feature

Hello, I would like to request

to have the context size less hard coded so that it can be configured after build.
Is it maybe even possible to implement per character?

As I understand it, the prompt, chat history and current request must fit in the context.
What happens in case of overflow, are the first messages from the history truncated? Or the prompt (if not cached)?

Also, I'd like to use, say, the full 8k context for the conversation history, but I don't want wikipedia-length responses.
How can I limit the length of the response to about 2k, but have an 8k history+prompt?

**Comment by amakropoulos** [comment]
Hi, thanks for the request!

How would you like to configure it after build?
One way could be to read it from a file and adjust it at Awake:
``` c#
    [DefaultExecutionOrder(-3)]
    public class Game : MonoBehaviour
    {
        LLM llm;
        public void Awake()
        {
               llm.contextSize = ...
        }
    }
```
It is not possible to adjust it per character, because it is one of the parameters of the LLM service when it starts (hardcoded from llama.cpp).

In case of overflow, the older chat history is discarded.
The way I have implemented it is that it always retains the prompt.
You can limit the response size with the `Num Predict` parameter (set it to 2000).

**Comment by 3inary** [comment]
Thanks, the [DefaultExecutionOrder(-3)] did the trick.
