### ISSUE TITLE
VisionOS iOS support

### ISSUE THREAD

**Issue by yosun** [undreamai/LLMUnity#74]
### Describe the feature

Hi! Is this supported on iOS/VisionOS?

**Comment by amakropoulos** [comment]
hi! not yet, but I get more and more requests about it.
I have to do an exploration to see how much effort is needed before prioritising it.

**Comment by yumianhuli2** [comment]
> hi! not yet, but I get more and more requests about it. I have to do an exploration to see how much effort is needed before prioritising it.

hi！When are you willing to support？thanks！

**Comment by amakropoulos** [comment]
For iOS the following adaptations are needed:

**iOS build** (for @amakropoulos )
- New DLL build of [LlamaLib](https://github.com/undreamai/LlamaLib)
- adapt the download function for setup of LLMUnity:
https://github.com/undreamai/LLMUnity/blob/5f94629010f8b7f268d77eb9fabff23772cc6fbf/Runtime/LLMUnitySetup.cs#L393-L429

**DLL loader**
- create a DLL loader similar to Android: https://github.com/undreamai/LLMUnity/blob/5f94629010f8b7f268d77eb9fabff23772cc6fbf/Runtime/LLMLib.cs#L241-L274
  and add it in the LibraryLoader functions:
https://github.com/undreamai/LLMUnity/blob/5f94629010f8b7f268d77eb9fabff23772cc6fbf/Runtime/LLMLib.cs#L107-L108
https://github.com/undreamai/LLMUnity/blob/5f94629010f8b7f268d77eb9fabff23772cc6fbf/Runtime/LLMLib.cs#L127-L128
https://github.com/undreamai/LLMUnity/blob/5f94629010f8b7f268d77eb9fabff23772cc6fbf/Runtime/LLMLib.cs#L146-L147
- add the DLL in the architectures and the DLL path
https://github.com/undreamai/LLMUnity/blob/5f94629010f8b7f268d77eb9fabff23772cc6fbf/Runtime/LLMLib.cs#L146-L147 (just "iOS" here)
https://github.com/undreamai/LLMUnity/blob/5f94629010f8b7f268d77eb9fabff23772cc6fbf/Runtime/LLMLib.cs#L445-L448 (the name of the DLL file here)

**Model extraction in iOS**
- similar extraction functions to Android - if files in the iOS build can't be accessed directly:
https://github.com/undreamai/LLMUnity/blob/5f94629010f8b7f268d77eb9fabff23772cc6fbf/Runtime/LLMUnitySetup.cs#L271-L326
- and use them here:
https://github.com/undreamai/LLMUnity/blob/5f94629010f8b7f268d77eb9fabff23772cc6fbf/Runtime/LLMManager.cs#L98-L153
https://github.com/undreamai/LLMUnity/blob/5f94629010f8b7f268d77eb9fabff23772cc6fbf/Runtime/LLMCharacter.cs#L355
- use persistentDataPath similarly to Android here: https://github.com/undreamai/LLMUnity/blob/5f94629010f8b7f268d77eb9fabff23772cc6fbf/Runtime/LLMUnitySetup.cs#L205-L210

**Runtime**
- check if iOS can run with all threads. in Android I have to limit it to the big cores only otherwise it takes forever:
https://github.com/undreamai/LLMUnity/blob/5f94629010f8b7f268d77eb9fabff23772cc6fbf/Runtime/LLM.cs#L401
The big cores calculation is here:
https://github.com/undreamai/LLMUnity/blob/5f94629010f8b7f268d77eb9fabff23772cc6fbf/Runtime/LLMUnitySetup.cs#L543-L591
